shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  bundeling:
    tsdown: ^0.19.0
  dev:
    bumpp: ^10.3.2
    changelogen: ^0.6.2
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^6.7.3
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  test:
    vitest: ^4.0.16
  types:
    '@types/node': ^24.10.7

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
