catalogs:
  bundeling:
    tsdown: ^0.12.9
  dev:
    bumpp: ^10.2.0
    changelogen: ^0.6.1
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.16.2
    eslint: ^9.30.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.0.13

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
